name: Publish Emacs to WinGet
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get latest Emacs version
        id: get_version
        shell: pwsh
        run: |
          $page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/"
          $latest_major = $page.Links | Where-Object { $_.href -match 'emacs-\d+/$' } | ForEach-Object { $_.href.TrimEnd('/') } | Sort-Object -Descending | Select-Object -First 1
          $installer_page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/"
          $latest_installer_name = $installer_page.Links | Where-Object { $_.href -match 'emacs-.*-installer.exe$' } | ForEach-Object { $_.href } | Sort-Object -Descending | Select-Object -First 1
          $url = "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/$latest_installer_name"
          $version = ($latest_installer_name -split '-')[-2]
          echo "URL=$url" >> $env:GITHUB_ENV
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "Complete URL: $url"

      - name: Download winget-create CLI
        shell: pwsh
        run: |
          $wingetCreateExe = "wingetcreate.exe"
          curl.exe -L "https://github.com/microsoft/winget-create/releases/download/v1.10.3.0/$wingetCreateExe" -o "$wingetCreateExe"
          echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create winget manifest
        run: '& "$PWD\wingetcreate.exe" update "GNU.Emacs" --urls "${{ env.URL }}|x64|nullsoft|machine" --version "${{ env.VERSION }}" --out .\manifests'

      - name: Create Pull Request
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          $repoDir = "winget-pkgs"
          git clone "https://github.com/${{ github.actor }}/winget-pkgs.git" $repoDir
          Set-Location $repoDir

          $branchName = "update-emacs-${{ env.VERSION }}"
          git checkout -b $branchName

          Copy-Item -Path "..\manifests\*" -Destination "manifests\g\GNU\Emacs\" -Recurse -Force

          git add .
          git commit -m "Update GNU.Emacs to ${{ env.VERSION }}"
          git push origin $branchName

          gh pr create --repo "microsoft/winget-pkgs" --base "master" --head "${{ github.actor }}:$branchName" --title "[New Package] GNU.Emacs ${{ env.VERSION }}" --body "This PR updates GNU.Emacs to version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}