name: Publish Emacs to WinGet
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get latest Emacs version
        id: get_version
        shell: pwsh
        run: |
          $page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/"
          $latest_major = $page.Links | Where-Object { $_.href -match 'emacs-\d+/$' } | ForEach-Object { $_.href.TrimEnd('/') } | Sort-Object -Descending | Select-Object -First 1
          $installer_page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/"
          $latest_installer = $installer_page.Links | Where-Object { $_.href -match 'emacs-.*-installer.exe$' } | ForEach-Object { $_.href } | Sort-Object -Descending | Select-Object -First 1
          $url = "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/$latest_installer"
          $version = ($latest_installer -split '-')[-2]
          echo "URL=$url" >> $env:GITHUB_ENV
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "Complete URL: $url"

      - name: Download Komac CLI
        shell: pwsh
        run: |
          $komacExe = "komac-2.12.1-x86_64-pc-windows-msvc.exe"
          curl.exe -L "https://github.com/russellbanks/Komac/releases/download/v2.12.1/$komacExe" -o "$komacExe"
          echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Publish to WinGet
        run: .\$komacExe update GNU.Emacs --urls ${{ env.URL }} --version ${{ env.VERSION }} --submit
        env:
          FORK_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
