name: Publish Emacs to WinGet
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get latest Emacs version
        id: get_version
        shell: pwsh
        run: |
          $page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/"
          $latest_major = $page.Links | Where-Object { $_.href -match 'emacs-\d+/$' } | ForEach-Object { $_.href.TrimEnd('/') } | Sort-Object -Descending | Select-Object -First 1
          $installer_page = Invoke-WebRequest -Uri "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/"
          $latest_installer_name = $installer_page.Links | Where-Object { $_.href -match 'emacs-.*-installer.exe$' } | ForEach-Object { $_.href } | Sort-Object -Descending | Select-Object -First 1
          $url = "https://ftp.gnu.org/gnu/emacs/windows/$latest_major/$latest_installer_name"
          $version = ($latest_installer_name -split '-')[-2]
          echo "URL=$url" >> $env:GITHUB_ENV
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "Complete URL: $url"

      - name: Download winget-create CLI
        shell: pwsh
        run: |
          $wingetCreateExe = "wingetcreate.exe"
          curl.exe -L "https://github.com/microsoft/winget-create/releases/download/v1.10.3.0/$wingetCreateExe" -o "$wingetCreateExe"
          echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create winget manifest
        run: '& "$PWD\wingetcreate.exe" update "GNU.Emacs" --urls "${{ env.URL }}" --version "${{ env.VERSION }}" --architecture x64 --out .\manifests'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update GNU.Emacs to ${{ env.VERSION }}"
          title: "[New Package] GNU.Emacs ${{ env.VERSION }}"
          body: "This PR updates GNU.Emacs to version ${{ env.VERSION }}."
          branch: "update-emacs-${{ env.VERSION }}"
          base: "master"
          path: "manifests/g/GNU/Emacs"
          repo: "microsoft/winget-pkgs"
          fork: "${{ github.actor }}/winget-pkgs"